version: "3.8"

services:
  tor-privoxy:
    image: dperson/torproxy
    volumes:
      - ./proxy:/etc/tor/torrc.d
    ports:
      - "9050:9050" # Tor proxy

  app:
    build: .
    depends_on:
      tor-privoxy:
        condition: service_healthy
    links:
      - tor-privoxy:tor
    environment:
      PROXY_HOST: tor
      CHROME_PATH: /usr/bin/chromium
    volumes:
      - ./results:/app/results:z
      - ./config:/app/config:z

  upload:
    build: ./upload
    volumes:
      - ./results:/app/ics:z
      - ./config:/app/credentials:z
